### PR TITLE
fix(#113): plugins downloader fix

### LINKED ISSUE #107: Add #if UNITY_EDITOR to editor-specific code
All scripts that rely on UnityEditor include (except BuildingSelectionUI.cs) must receive this treatment to prevent issues with project building

### LINKED ISSUE #113: Fix plugins downloader to work with compilation errors caused by not having plugins

### PR DESCRIPTION
**Pull request by StaszkeKun**
Reorganized our assembly structure, since Unity's editor assembly requires an `Assets/Editor/*` path and our editor scripts have `Assets/Scripts/Editor/*`.

There are now 4 our assemblies:
- Cosmobot
    - depending on: `Unity.TextMeshPro`, `Unity.InputSystem`, `Cosmobot.Utils`
    - root namespace: `Cosmobot`
    - path: `Assets/Scripts/*`
    - contains most of our scripts
    - included on all platforms
- Cosmobot.Editor
    - depending on: `Cosmobot.Utils`, `Cosmobot`
    - root namespace: `Cosmobot.Editor`
    - path: `Assets/Scripts/Editor/*`
    - contains only our Unity Editor scripts, that depend on main assembly code
    - included only in Editor
- Cosmobot.Editor.Standalone
    - depending on: `Cosmobot.Utils`
    - root namespace: `Cosmobot.Editor.Standalone`
    - path: `Assets/Scripts/Editor/EditorStandalone/*`
    - contains only our Unity Editor scripts, that will work on their own
    - included only in Editor
- Cosmobot.Utils
    - doesn't depend on anything
    - root namespace: `Cosmobot.Utils`
    - path: `Assets/Scripts/Utils/*`
    - contains our utility scripts that can be required by assemblies mentioned above 
    - included on all platforms

Please, from now on, place Editor and Utils scripts in their corresponding directories, and also use their assigned root namespaces.

Closes #113
Closes #107

### CODE REVIEW

**Review by PatrykPaluch — CHANGES_REQUESTED** [review]
dc

**Comment by PatrykPaluch** [comment]
This will also close #107

**Review by PatrykPaluch — APPROVED** [review]
gj
